Vagrant.configure(2) do |config|
  config.vm.box  = 'ubuntu/trusty64'
  config.vm.synced_folder "..", "/vagrant_data"
  config.vm.provision "shell", path: "script.sh"
  config.vm.network :forwarded_port, guest: 8000, host: 8000, auto_correct: true
end
